@TrabalhoAPI_HostAddress = http://localhost:5041

### LISTAR PRODUTOS
GET {{TrabalhoAPI_HostAddress}}/api/Produto
Accept: application/json


### CRIAR PRODUTO
POST {{TrabalhoAPI_HostAddress}}/api/Produto
Content-Type: application/json

{
  "nome": "Mouse Gamer",
  "preco": 150.00
}


### ATUALIZAR PRODUTO (trocar ID)
PUT {{TrabalhoAPI_HostAddress}}/api/Produto/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Mouse Atualizado",
  "preco": 180.00
}


### REMOVER PRODUTO (trocar ID)
DELETE {{TrabalhoAPI_HostAddress}}/api/Produto/1